export const products = [
  {
    id: 1,
    name: "Elysian Gold Herb",
    category: "Woody Oriental",
    notes: "Sandalwood, Bergamot, Vanilla",
    topNotes: "Calabrian Bergamot, Pink Pepper",
    heartNotes: "Iris, Bulgarian Rose, Jasmine",
    baseNotes: "Mysore Sandalwood, Bourbon Vanilla, Ambergris",
    price: 450000,
    priceFormatted: "Rp 450.000",
    image: "https://images.unsplash.com/photo-1594035910387-fea47794261f?q=80&w=800&auto=format&fit=crop",
    rating: 4.9,
    reviewsCount: 128,
    description: "Perpaduan hangat antara kayu cendana eksotis dan manisnya vanila bourbon yang memberikan aura kemewahan tak lekang oleh waktu. Sempurna untuk malam formal atau acara eksklusif.",
    aiVerdict: "Cocok untuk kepribadian yang tenang, elegan, dan menyukai kehangatan rempah alami."
  },
  {
    id: 2,
    name: "Midnight Velour",
    category: "Gourmand Oud",
    notes: "Amber, Oud, Damask Rose",
    topNotes: "Blackcurrant, Saffron",
    heartNotes: "Damask Rose, Patchouli",
    baseNotes: "Agarwood (Oud), Black Amber, Leather",
    price: 580000,
    priceFormatted: "Rp 580.000",
    image: "https://images.unsplash.com/photo-1541643600914-78b084683601?q=80&w=800&auto=format&fit=crop",
    rating: 4.8,
    reviewsCount: 94,
    description: "Aroma malam yang misterius dan menggoda dengan inti bunga mawar damaskus yang dibalut kepekatan gaharu (oud) dan kelembutan kulit mewah.",
    aiVerdict: "Pilihan utama untuk menciptakan kesan pertama yang berwibawa, karismatik, dan sulit dilupakan."
  },
  {
    id: 3,
    name: "Verdant Breeze",
    category: "Fresh Green",
    notes: "Green Tea, Jasmine, Mint",
    topNotes: "Crushed Peppermint, Sicilian Lemon",
    heartNotes: "Green Tea Leaves, White Jasmine",
    baseNotes: "White Musk, Oakmoss",
    price: 390000,
    priceFormatted: "Rp 390.000",
    image: "https://images.unsplash.com/photo-1523293182086-7651a899d37f?q=80&w=800&auto=format&fit=crop",
    rating: 4.7,
    reviewsCount: 210,
    description: "Kesejukan embun pagi di kebun teh dataran tinggi. Memberikan kesegaran instan yang menenangkan pikiran di tengah padatnya aktivitas urban.",
    aiVerdict: "Sangat direkomendasikan untuk cuaca tropis yang terik dan aktivitas luar ruangan sepanjang hari."
  },
  {
    id: 4,
    name: "Royal Blossom",
    category: "White Floral",
    notes: "Tuberose, Iris, White Musk",
    topNotes: "Neroli, Pear Blossom",
    heartNotes: "Tuberose absolute, Florentine Iris",
    baseNotes: "Cashmere Wood, White Musk",
    price: 499000,
    priceFormatted: "Rp 499.000",
    image: "https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?q=80&w=800&auto=format&fit=crop",
    rating: 4.9,
    reviewsCount: 156,
    description: "Simfoni bunga putih yang memancarkan pesona feminin dan kemurnian. Wangi semerbak tuberose berpadu anggun dengan kelembutan iris.",
    aiVerdict: "Cocok untuk suasana romantis, pesta pernikahan, atau kencan makan malam."
  },
  {
    id: 5,
    name: "Bois d'Elegance",
    category: "Woody Aromatic",
    notes: "Cedarwood, Vetiver, Cardamom",
    topNotes: "Guatemalan Cardamom, Cypress",
    heartNotes: "Haitian Vetiver, Violet Leaf",
    baseNotes: "Virginia Cedarwood, Amber",
    price: 520000,
    priceFormatted: "Rp 520.000",
    image: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?q=80&w=800&auto=format&fit=crop",
    rating: 4.8,
    reviewsCount: 82,
    description: "Aroma maskulin kontemporer dengan dominasi kayu cedar yang tajam namun diseimbangkan oleh kehangatan kapulaga dan kesegaran vetiver.",
    aiVerdict: "Merefleksikan profesionalisme, kepercayaan diri tinggi, dan ketegasan dalam mengambil keputusan."
  },
  {
    id: 6,
    name: "Citrus Lumière",
    category: "Citrus Fresh",
    notes: "Mandarin, Grapefruit, Vetiver",
    topNotes: "Blood Orange, Red Grapefruit",
    heartNotes: "Orange Blossom, Neroli",
    baseNotes: "Smoky Vetiver, Cedar",
    price: 410000,
    priceFormatted: "Rp 410.000",
    image: "https://images.unsplash.com/photo-1615397349754-cfa2066a298e?q=80&w=800&auto=format&fit=crop",
    rating: 4.6,
    reviewsCount: 115,
    description: "Ledakan energi dari jeruk mandarin Mediterania yang berpadu dengan kehangatan asap kayu tipis. Pembangkit semangat terbaik di awal hari.",
    aiVerdict: "Meningkatkan mood, energi produktivitas, dan memberikan kesan awet muda serta dinamis."
  },
  {
    id: 7,
    name: "Aura de Fleur",
    category: "Floral Fruity",
    notes: "Peony, Lychee, Cedarwood",
    topNotes: "Exotic Lychee, Rhubarb",
    heartNotes: "Pink Peony, Turkish Rose",
    baseNotes: "Cashmeran, Cedarwood",
    price: 475000,
    priceFormatted: "Rp 475.000",
    image: "https://images.unsplash.com/photo-1547887537-6158d64c35b3?q=80&w=800&auto=format&fit=crop",
    rating: 4.9,
    reviewsCount: 204,
    description: "Sensasi manis dan segar buah leci matang yang membuka jalan menuju keharuman bunga peony merah muda yang mekar penuh di taman kerajaan.",
    aiVerdict: "Wewangian serbaguna yang sangat digemari untuk aktivitas santai maupun pertemuan semi-formal."
  },
  {
    id: 8,
    name: "Velvet Oud Absolute",
    category: "Gourmand Oud",
    notes: "Pure Agarwood, Praline, Incense",
    topNotes: "Incense Smoke, Cinnamon",
    heartNotes: "Praline, Clove absolute",
    baseNotes: "Royal Cambodian Oud, Benzoin",
    price: 750000,
    priceFormatted: "Rp 750.000",
    image: "https://images.unsplash.com/photo-1528740561666-dc2479dc08ab?q=80&w=800&auto=format&fit=crop",
    rating: 5.0,
    reviewsCount: 64,
    description: "Karya puncak olfaktori dengan gaharu Kamboja asli yang disiram lelehan karamel praline hangat dan kepulan asap dupa suci. Edisi kolektor terbatas.",
    aiVerdict: "Wewangian level tertinggi bagi penikmat parfum sejati (*fragrance connoisseur*)."
  }
];
